[pytest]
minversion = 6.0

pythonpath = . src
testpaths = . tests

addopts = -ra --strict-markers --cov=src --cov-fail-under=70 --cov-report=term --cov-report=html:./data/monitoring/pytest_report

filterwarnings = 
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning
    ignore::FutureWarning

asyncio_mode = auto
cache_dir = .cache/.pytest_cache

console_output_style = progress2
log_cli = true
log_cli_level = INFO

markers =
    auth: Mark tests related to authentication(deselect with '-m"not auth"')
    database: Mark tests related to database operations(deselect with '-m"not database"')
    api: Mark tests related to API endpoints(deselect with '-m"not api"')
    integration: Mark integration tests(deselect with '-m"not integration"')
    unit: Mark unit tests(deselect with '-m"not unit"')
    performance: Mark performance tests(deselect with '-m"not performance"')
    security: Mark security tests(deselect with '-m"not security"')
    slow: Mark slow-running tests(deselect with '-m"not slow"')
    e2e: Mark end to end tests(deselect with '-m"not e2e"')
    data: marks tests that require large datasets(deselect with '-m"not data"')